#sequenceid的sql
CREATE TABLE shark_sequenceid(
	s_id INT NOT NULL AUTO_INCREMENT COMMENT '主键',
	s_type INT NOT NULL COMMENT '类型',
	s_useData BIGINT NOT NULL COMMENT '申请占位数量',
	PRIMARY KEY (s_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

#读写分离sql
CREATE DATABASE master_test;
CREATE TABLE userinfo_test(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE slave_test;
CREATE TABLE userinfo_test(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

#表名连续的多库多片模式sql
CREATE DATABASE db_0000;
CREATE TABLE userinfo_test_0000(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE userinfo_test_0001(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0000(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0001(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE DATABASE db_0001;
CREATE TABLE userinfo_test_0002(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE userinfo_test_0003(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0002(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0003(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

#非表名连续的多库多片模式sql
CREATE DATABASE db_0000;
CREATE TABLE userinfo_test_0000(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE userinfo_test_0001(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0000(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0001(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE DATABASE db_0001;
CREATE TABLE userinfo_test_0000(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE userinfo_test_0001(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0000(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0001(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;

#单库多片模式sql
CREATE DATABASE db_test;
CREATE TABLE userinfo_test_0000(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0000(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE userinfo_test_0001(
	uid BIGINT NOT NULL COMMENT '主键',
	userName VARCHAR(20) NOT NULL COMMENT '类型',
	PRIMARY KEY (uid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE email_test_0001(
	email VARCHAR(80) NOT NULL COMMENT '主键',
	email_hash BIGINT NOT NULL COMMENT '主键的hash值/路由条件',
	uid BIGINT NOT NULL COMMENT '主键/路由条件',
	PRIMARY KEY (email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin;